name: SonarCloud analysis
on:
  push:
    branches: [ main ]
    paths:
      - 'src/**'
      - '**/*.lock'
      - '**/*.toml'
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'src/**'
      - '**/*.lock'
      - '**/*.toml'
jobs:
  sonarqube:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - uses: dtolnay/rust-toolchain@stable
        with: { components: clippy }
      - uses: SonarSource/sonarqube-scan-action@v6
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
